# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-21 18:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewsManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewee', models.CharField(max_length=128)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(max_length=500)),
                ('stars', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Roof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=128)),
                ('website', models.CharField(max_length=128)),
                ('phone_no', models.CharField(max_length=128)),
                ('burough', models.CharField(max_length=128)),
                ('pictureURL', models.CharField(max_length=128)),
                ('calculated_rank', models.IntegerField()),
                ('price_rank', models.IntegerField()),
                ('location_rank', models.IntegerField()),
                ('fun_rank', models.IntegerField()),
                ('view_rank', models.IntegerField()),
                ('crowd_rank', models.IntegerField()),
                ('crowd_type', models.CharField(max_length=128)),
                ('rose_price', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='reviewsmanager',
            name='roof',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='roofs.Roof'),
        ),
    ]
